// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6cITLc3ZtaQut2GvorYH6z7jw-G_UXaA',
    appId: '1:899719777791:web:0ef7c50b59c100e50eebca',
    messagingSenderId: '899719777791',
    projectId: 'edu-pilot-923ec',
    authDomain: 'edu-pilot-923ec.firebaseapp.com',
    storageBucket: 'edu-pilot-923ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxLgNkYZ3-NYTt3z4V6mOsKeiSb4lVMlw',
    appId: '1:899719777791:android:be578b1d48c8a4160eebca',
    messagingSenderId: '899719777791',
    projectId: 'edu-pilot-923ec',
    storageBucket: 'edu-pilot-923ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5r0ZEv_NONZJkRA0m7SORcolD9sY6mw0',
    appId: '1:899719777791:ios:8f048e3dd24e2d440eebca',
    messagingSenderId: '899719777791',
    projectId: 'edu-pilot-923ec',
    storageBucket: 'edu-pilot-923ec.firebasestorage.app',
    iosBundleId: 'com.example.edupilot',
  );
}
